apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crda-app
  template:
    metadata:
      labels:
        app: crda-app
    spec:
      containers:
      - name: crda-app
        image: your-dockerhub-username/crda-app:latest
        ports:
        - containerPort: 4200
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: base_crda
---
apiVersion: v1
kind: Service
metadata:
  name: crda-service
spec:
  type: LoadBalancer
  selector:
    app: crda-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200