apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: votre_nom_d'utilisateur/mon-application-notification:latest
        ports:
        - containerPort: 3003
        resources:
          limits:
            memory: "256Mi" # Limite de mémoire à 256 MiB
            cpu: "500m"     # Limite de CPU à 0.5 unité (500 milli-CPU)
          requests:
            memory: "128Mi" # Demande de mémoire de 128 MiB
            cpu: "250m"     # Demande de CPU de 0.25 unité (250 milli-CPU)
