apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring
        image: votre_nom_d'utilisateur/mon-application-monitoring:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "512Mi" # Limite de mémoire à 512 MiB
            cpu: "1000m"     # Limite de CPU à 1 unité (1000 milli-CPU)
          requests:
            memory: "256Mi" # Demande de mémoire de 256 MiB
            cpu: "500m"     # Demande de CPU de 0.5 unité (500 milli-CPU)
