apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
      - name: document
        image: votre_nom_d'utilisateur/document:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"  # Limite de CPU à 500 milicoeurs
            memory: "256Mi"  # Limite de mémoire à 256 Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: votre_nom_d'utilisateur/user:latest
        ports:
        - containerPort: 4000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
